### ISSUE TITLE
Migrating Sveltekit v1 + graphQL, eg: `~/posts.json` throws: internal server 500

### ISSUE THREAD

**Issue by inspiredlabs** [inspiredlabs/hygraph#1]
This tutorial @22mins shows how to use `~/posts.json` from an GraphQL endpoint: https://www.youtube.com/watch?v=zH2qG9YwN3s

There seems to be some difficulty migrating this syntax according to the docs: https://github.com/sveltejs/kit/issues/8885

I am looking to migrate this Sveltekit repository to v1: https://hygraph.com/blog/how-to-get-started-with-sveltekit-and-graphql

You can see the current endpoint here: https://github.com/inspiredlabs/hygraph/tree/master/src/routes/posts.json

**Comment by spences10** [comment]
Fixed with #2

**Comment by inspiredlabs** [comment]
Thanks, Scott. I've noticed that step is working fine now, but `return props: { posts } }` etc. won't work from `+page.svelte`. So I'm going to have a look at the [graphcms-svelte-starter](https://scottspence.com/posts/graphcms-svelte-starter), as recommended.
